name: Release Docker Image

on:
    release:
        types: [created]

jobs:
    call-workflow-passing-data:
        uses: zakred/github-workflows/.github/workflows/docker-build-push.yml@v1
        secrets:
            DOCKER_REGISTRY_SECRET: ${{ secrets.DOCKER_REGISTRY_SECRET }}
            DOCKER_REGISTRY_USER: zakred
            DOCKER_IMAGE_NAME: zakred/fight-tracker-service:${{github.ref_name}}
            DOCKER_CONTEXT_PATH: .
